In [1]:
# Install Libraries
!pip install pandas pymysql sqlalchemy

Requirement already satisfied: pandas in c:\users\umana\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: pymysql in c:\users\umana\anaconda3\lib\site-packages (1.1.1)
Requirement already satisfied: sqlalchemy in c:\users\umana\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: numpy>=1.26.0 in c:\users\umana\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\umana\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\umana\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\umana\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\umana\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\umana\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: six>=1.5 in c:\users\umana\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import pandas as pd
from sqlalchemy import create_engine

customer_data = {

    "CustomerID":[1,2,3,4,5,6,7,8,9,10,2],
    "CustomerName":["Amit Sharma", "Priya Rao", "Rahul Verma", "Sneha Iyer", "Kiran Kumar", "Anjali Gupta", "Vikram Singh", "Neha Patel", "Arjun Reddy", "Meera Nair", "Priya Rao"],
    "City":["Delhi","Chennai", "Mumbai", "Bengaluru", "Hyderabad", "Pune", "Delhi", "Ahmedabad", "Chennai", "Kochi", "Chennai"],
    "Email":["amit@gmail.com", "priya@gmail.com", "rahul@gmail.com", "sneha@gmail.com", "kiran@gmail.com", "anjali@gmail.com", "vikram@gmail.com", "neha@gmail.com", "arjun@gmail.com", "meera@gmail.com", "priya@gmail.com"],
    "Age":[28,34,41,29,37,26,None,31,39,27,34],
    "JoinDate":["2025-01-10", "2025-01-15", "2025-02-02", "2025-02-12", "2025-03-05", "2025-03-15", "2025-04-01", "2025-04-10", "2025-05-02", "2025-05-18", "2025-01-15"],
    "TotalPurchase":[12500, 22000, 18500, 9800, 31000, 7600, None, 15400, 27800, 11200, 22000]}

df = pd.DataFrame(customer_data)
df

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,1,Amit Sharma,Delhi,amit@gmail.com,28.0,2025-01-10,12500.0
1,2,Priya Rao,Chennai,priya@gmail.com,34.0,2025-01-15,22000.0
2,3,Rahul Verma,Mumbai,rahul@gmail.com,41.0,2025-02-02,18500.0
3,4,Sneha Iyer,Bengaluru,sneha@gmail.com,29.0,2025-02-12,9800.0
4,5,Kiran Kumar,Hyderabad,kiran@gmail.com,37.0,2025-03-05,31000.0
5,6,Anjali Gupta,Pune,anjali@gmail.com,26.0,2025-03-15,7600.0
6,7,Vikram Singh,Delhi,vikram@gmail.com,NaN,2025-04-01,NaN
7,8,Neha Patel,Ahmedabad,neha@gmail.com,31.0,2025-04-10,15400.0
8,9,Arjun Reddy,Chennai,arjun@gmail.com,39.0,2025-05-02,27800.0
9,10,Meera Nair,Kochi,meera@gmail.com,27.0,2025-05-18,11200.0
10,2,Priya Rao,Chennai,priya@gmail.com,34.0,2025-01-15,22000.0

In [4]:
df.to_csv("customers.csv", index=False)
print("CSV Created Successfully")

CSV Created Successfully

In [5]:
customer_df = pd.read_csv("customers.csv")
customer_df

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,1,Amit Sharma,Delhi,amit@gmail.com,28.0,2025-01-10,12500.0
1,2,Priya Rao,Chennai,priya@gmail.com,34.0,2025-01-15,22000.0
2,3,Rahul Verma,Mumbai,rahul@gmail.com,41.0,2025-02-02,18500.0
3,4,Sneha Iyer,Bengaluru,sneha@gmail.com,29.0,2025-02-12,9800.0
4,5,Kiran Kumar,Hyderabad,kiran@gmail.com,37.0,2025-03-05,31000.0
5,6,Anjali Gupta,Pune,anjali@gmail.com,26.0,2025-03-15,7600.0
6,7,Vikram Singh,Delhi,vikram@gmail.com,NaN,2025-04-01,NaN
7,8,Neha Patel,Ahmedabad,neha@gmail.com,31.0,2025-04-10,15400.0
8,9,Arjun Reddy,Chennai,arjun@gmail.com,39.0,2025-05-02,27800.0
9,10,Meera Nair,Kochi,meera@gmail.com,27.0,2025-05-18,11200.0
10,2,Priya Rao,Chennai,priya@gmail.com,34.0,2025-01-15,22000.0

In [6]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     11 non-null     int64
 1   CustomerName   11 non-null     object
 2   City           11 non-null     object
 3   Email          11 non-null     object
 4   Age            10 non-null     float64
 5   JoinDate       11 non-null     object
 6   TotalPurchase  10 non-null     float64
dtypes: float64(2), int64(1), object(4)
memory usage: 748.0+ bytes

In [7]:
customer_df.isnull().sum()

CustomerID       0
CustomerName     0
City             0
Email            0
Age              1
JoinDate         0
TotalPurchase    1
dtype: int64

In [10]:
customer_df["Age"] = customer_df["Age"].fillna(
    customer_df["Age"].mean())
customer_df["TotalPurchase"] = customer_df["TotalPurchase"].fillna(0)

In [11]:
customer_df.shape

(11, 7)

In [14]:
customer_df = customer_df.drop_duplicates()
customer_df.shape

(10, 7)

In [15]:
customer_df["CustomerID"] = customer_df["CustomerID"].astype(int)
customer_df["Age"] = customer_df["Age"].astype(int)
customer_df["JoinDate"] = pd.to_datetime(
customer_df["JoinDate"])

In [16]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     10 non-null     int32
 1   CustomerName   10 non-null     object
 2   City           10 non-null     object
 3   Email          10 non-null     object
 4   Age            10 non-null     int32
 5   JoinDate       10 non-null     datetime64[ns]
 6   TotalPurchase  10 non-null     float64
dtypes: datetime64[ns](1), float64(1), int32(2), object(3)
memory usage: 560.0+ bytes

In [17]:
total_revenue = customer_df["TotalPurchase"].sum()
print("Total Revenue =", total_revenue)

Total Revenue = 155800.0

In [18]:
city_revenue = customer_df.groupby("City")["TotalPurchase"].sum().reset_index()
city_revenue

        City  TotalPurchase
0  Ahmedabad        15400.0
1  Bengaluru         9800.0
2    Chennai        49800.0
3      Delhi        12500.0
4  Hyderabad        31000.0
5      Kochi        11200.0
6     Mumbai        18500.0
7       Pune         7600.0

In [19]:
city_customer_count = customer_df.groupby("City")["CustomerID"].count().reset_index()
city_customer_count

        City  CustomerID
0  Ahmedabad           1
1  Bengaluru           1
2    Chennai           2
3      Delhi           2
4  Hyderabad           1
5      Kochi           1
6     Mumbai           1
7       Pune           1

In [26]:
engine = create_engine(
    "mysql+pymysql://root:mysql@127.0.0.1:3306/customer_etl")
engine

Engine(mysql+pymysql://root:***@127.0.0.1:3306/customer_etl)

In [27]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT DATABASE();"))
    print(result.fetchone())

('customer_etl',)

In [28]:
# 4.Find top customers by purchase.
customer_df.to_sql(
    name="customers_fact",
    con=engine,
    if_exists="replace",
    index=False)
print("Customers Loaded")

Customers Loaded

In [29]:
# 5.Analyze city-wise revenue
pd.read_sql("""SELECT City, SUM(TotalPurchase) Revenue FROM customers_fact
GROUP BY City ORDER BY Revenue DESC""",con=engine)

        City  Revenue
0    Chennai  49800.0
1  Hyderabad  31000.0
2     Mumbai  18500.0
3  Ahmedabad  15400.0
4      Delhi  12500.0
5      Kochi  11200.0
6  Bengaluru   9800.0
7       Pune   7600.0

In [30]:
# 6.Rank customers using window functions
pd.read_sql("""SELECT CustomerName, TotalPurchase,
RANK() OVER(ORDER BY TotalPurchase DESC) AS CustomerRank FROM customers_fact""",con=engine)

   CustomerName  TotalPurchase  CustomerRank
0   Kiran Kumar        31000.0             1
1   Arjun Reddy        27800.0             2
2     Priya Rao        22000.0             3
3   Rahul Verma        18500.0             4
4    Neha Patel        15400.0             5
5   Amit Sharma        12500.0             6
6    Meera Nair        11200.0             7
7    Sneha Iyer         9800.0             8
8  Anjali Gupta         7600.0             9
9  Vikram Singh            0.0            10

In [31]:
# 7. Total Customers
pd.read_sql("""SELECT COUNT(*) AS TotalCustomers FROM customers_fact""",con=engine)

   TotalCustomers
0              10

In [32]:
# 8. City-wise Customer Count
pd.read_sql("""SELECT City, COUNT(*) AS CustomerCount FROM customers_fact GROUP BY City""",con=engine)

        City  CustomerCount
0      Delhi              2
1    Chennai              2
2     Mumbai              1
3  Bengaluru              1
4  Hyderabad              1
5       Pune              1
6  Ahmedabad              1
7      Kochi              1

In [33]:
# 9. City-wise Revenue
pd.read_sql("""SELECT City, SUM(TotalPurchase) AS Revenue FROM customers_fact GROUP BY City""",con=engine)

        City  Revenue
0      Delhi  12500.0
1    Chennai  49800.0
2     Mumbai  18500.0
3  Bengaluru   9800.0
4  Hyderabad  31000.0
5       Pune   7600.0
6  Ahmedabad  15400.0
7      Kochi  11200.0

In [34]:
# 10. fetch Above Average Customers information
pd.read_sql("""SELECT *FROM customers_fact WHERE TotalPurchase >
(SELECT AVG(TotalPurchase) FROM customers_fact)""",con=engine)

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,2,Priya Rao,Chennai,priya@gmail.com,34,2025-01-15,22000.0
1,3,Rahul Verma,Mumbai,rahul@gmail.com,41,2025-02-02,18500.0
2,5,Kiran Kumar,Hyderabad,kiran@gmail.com,37,2025-03-05,31000.0
3,9,Arjun Reddy,Chennai,arjun@gmail.com,39,2025-05-02,27800.0

In [35]:
# 11. find Customer Acquisition Trend
pd.read_sql("""SELECT MONTH(JoinDate) AS MonthNo,
COUNT(*) AS NewCustomers FROM customers_fact GROUP BY MONTH(JoinDate) ORDER BY MonthNo""",con=engine)

   MonthNo  NewCustomers
0        1             2
1        2             2
2        3             2
3        4             2
4        5             2